config/routes.rb
Rails.application.routes.draw do
  get 'observations/gallery'
  resources :birds
  devise_for :users
  resources :observations
  root 'observations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bird.rb
class Bird < ApplicationRecord
  has_one :observation
  validates :name, presence: true, uniqueness: true
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :user
  has_one :bird
  validates :name, uniqueness: { scope: :season, message: "should be added once per season" }
  validates :max_number, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :observations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  before_action :set_bird, only: %i[ show edit update destroy ]

  # GET /birds or /birds.json
  def index
    @birds = Bird.all
  end

  # GET /birds/1 or /birds/1.json
  def show
  end

  # GET /birds/new
  def new
    @bird = Bird.new
  end

  # GET /birds/1/edit
  def edit
  end

  # POST /birds or /birds.json
  def create
    @bird = Bird.new(bird_params)

    respond_to do |format|
      if @bird.save
        format.html { redirect_to @bird, notice: "Bird was successfully created." }
        format.json { render :show, status: :created, location: @bird }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /birds/1 or /birds/1.json
  def update
    respond_to do |format|
      if @bird.update(bird_params)
        format.html { redirect_to @bird, notice: "Bird was successfully updated." }
        format.json { render :show, status: :ok, location: @bird }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1 or /birds/1.json
  def destroy
    @bird.destroy
    respond_to do |format|
      format.html { redirect_to birds_url, notice: "Bird was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bird
      @bird = Bird.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bird_params
      params.require(:bird).permit(:name, :image)
    end
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_action :set_observation, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]

  # GET /observations or /observations.json
  def index
    @observations = Observation.all
  end

  # GET /observations/1 or /observations/1.json
  def show
  end

  # GET /observations/new
  def new
    @observation = current_user.observations.build
  end

  # GET /observations/1/edit
  def edit
  end

  def gallery
  end

  # POST /observations or /observations.json
  def create
    @observation = current_user.observations.build(observation_params)

    respond_to do |format|
      if @observation.save
        format.html { redirect_to @observation, notice: "Observation was successfully created." }
        format.json { render :show, status: :created, location: @observation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /observations/1 or /observations/1.json
  def update
    respond_to do |format|
      if @observation.update(observation_params)
        format.html { redirect_to @observation, notice: "Observation was successfully updated." }
        format.json { render :show, status: :ok, location: @observation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /observations/1 or /observations/1.json
  def destroy
    @observation.destroy
    respond_to do |format|
      format.html { redirect_to observations_url, notice: "Observation was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_observation
      @observation = Observation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def observation_params
      params.require(:observation).permit(:season, :name, :max_number, :notes, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/views/birds/_form.html.erb
<%= form_with(model: bird) do |form| %>
  <% if bird.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

      <ul>
        <% bird.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name,  class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :image %>
    <%= form.text_field :image,  class:"form-control" %>
  </div>

  <br />

  <div class="actions">
    <%= form.submit class:"btn btn-warning btn-lg" %>
  </div>
<% end %>

app/views/birds/edit.html.erb
<h2>Editing Bird</h2>

<%= render 'form', bird: @bird %>
<br />
<%= link_to 'Show', @bird, class:"btn btn-warning btn-sm me-2" %> 
<%= link_to 'Back', birds_path, class:"btn btn-warning btn-sm" %>

app/views/birds/index.html.erb
<h2>Birds</h2>

<table class="table table-bordered table-sm table-striped">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @birds.each do |bird| %>
      <tr>
        <td><%= bird.name %></td>
        <td><%= bird.image %></td>
        <td><%= link_to 'Show', bird %></td>
        <td><%= link_to 'Edit', edit_bird_path(bird) %></td>
        <td><%= link_to 'Delete', bird, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Bird', new_bird_path, class:"btn btn-warning btn-lg" %>

app/views/birds/new.html.erb
<h2>New Bird</h2>

<%= render 'form', bird: @bird %>
<br/>
<%= link_to 'Back', birds_path, class:"btn btn-warning btn-sm" %>

app/views/birds/show.html.erb
<div class="card" style="width: 40rem; margin: auto;">
  <%= image_tag(@bird.image) %>
  <div class="card-body">
    <h3 class="card-title">
      <%= @bird.name %>
    </h3>
    <%= link_to 'Edit', edit_bird_path(@bird), class:"btn btn-warning btn-sm me-2" %> 
    <%= link_to 'Back', birds_path, class:"btn btn-warning btn-sm" %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Birdfeeder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'observations/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/observations/_form.html.erb
<%= form_with(model: observation) do |form| %>
  <% if observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(observation.errors.count, "error") %> prohibited this observation from being saved:</h2>

      <ul>
        <% observation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :season %>
    <%= form.text_field :season, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.select :name, Bird.all.collect { |bird| [ bird.name ] }, { include_blank: true }, class:"form-select mb-3" %>
  </div>

  <div class="field mb-3">
    <%= form.label :max_number %>
    <%= form.number_field :max_number, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :notes %>
    <%= form.text_field :notes, class:"form-control" %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :observation_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <br />

  <div class="actions">
    <%= form.submit class:"btn btn-warning btn-lg" %>
  </div>
<% end %>

app/views/observations/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'BIRD FEEDER', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Gallery', observations_gallery_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
          <% if current_user.admin %>
            <li class="nav-item">
              <%= link_to 'Birds', birds_path, class:"nav-link" %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <div class="text-end">
        <% if user_signed_in? %>
        <button type="button" class="btn btn-warning btn-sm">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, style:"text-decoration:none; color:#000;" %>
        </button>
        <% else %>
        <button type="button" class="btn btn-warning btn-sm me-2">
          <%= link_to 'Log In', new_user_session_path, style:"text-decoration:none; color:#000;" %>
        </button>
        <button type="button" class="btn btn-warning btn-sm">
          <%= link_to 'Sign Up', new_user_registration_path, style:"text-decoration:none; color:#000;" %>
        </button>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/observations/edit.html.erb
<br />
<h2>Edit Observation</h2>

<%= render 'form', observation: @observation %>
<br />
<%= link_to 'Show', @observation, class:"btn btn-warning btn-sm me-3" %> 
<%= link_to 'Back', observations_path, class:"btn btn-warning btn-sm me-3" %>
<%= link_to 'Delete', @observation, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %>

app/views/observations/gallery.html.erb
<% @bird_names = Observation.where(user_id: current_user.id).all.collect { |obs| [ obs.name ] } %><br/>

<div class="row row-cols-1 row-cols-md-3">    
  <% @bird_names.each do |name| %>
    <% @bird_id = Bird.where(name: name.flatten).ids %>
    <% @bird_img = Bird.find(@bird_id).collect { |bird| [bird.image] } %>
    <% @image = @bird_img.flatten %>

    <div class="card" style="padding:0;max-width:100%;height:auto;">  
      <%= image_tag(@image[0]) %>
    </div>

  <% end %>
</div>

app/views/observations/index.html.erb
<% if user_signed_in? %>

  <h2>My Observations</h2>

  <table class="table table-bordered table-sm table-striped">
    <thead class="table-dark">
      <tr>
        <th>Season</th>
        <th>Name</th>
        <th>Max number</th>
        <th>Notes</th>
      </tr>
    </thead>

    <tbody>
      <% @observations.each do |observation| %>
        <% if observation.user == current_user %>
        <tr>
          <td><%= observation.season %></td>
          <td><%= link_to observation.name, observation %></td>
          <td><%= observation.max_number %></td>
          <td><%= observation.notes %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add Observation', new_observation_path, class:"btn btn-warning btn-lg" %>

<% else %>
<div class="container">
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner" style="padding:0;max-width:100%;height:auto;">
      <div class="carousel-item active">
        <%= image_tag("feeder1") %>
      </div>
      <div class="carousel-item">
        <%= image_tag("feeder2") %>
      </div>
      <div class="carousel-item">
        <%= image_tag("feeder3") %>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<% end %>

app/views/observations/new.html.erb
<br />
<h2>Add Observation</h2>

<%= render 'form', observation: @observation %>
<br />
<%= link_to 'Back', observations_path, class:"btn btn-warning btn-sm" %>

app/views/observations/show.html.erb
<div class="card" style="width: 40rem; margin: auto;">
  <% 
    @bird_id = Bird.where(name: @observation.name).ids 
    @bird_img = Bird.find(@bird_id[0]).image
  %>
  <%= image_tag( @bird_img ) %>
  <div class="card-body">
    <h3 class="card-title">
      <%= @observation.name %>
    </h3>
    <%= link_to 'Edit', edit_observation_path(@observation), class:"btn btn-warning btn-sm me-2" %> 
    <%= link_to 'Back', observations_path, class:"btn btn-warning btn-sm" %>
  </div>
</div>